import pyautogui
import time

start_time = time.time()

pyautogui.click(134, 860)
time.sleep(2)
pyautogui.click(810, 260)
pyautogui.moveTo(-20, -20, duration=0)
time.sleep(30)

pyautogui.write('num_rows = len(rowSum)', interval = 0.05)
pyautogui.press("enter")
pyautogui.write('num_cols = len(colSum)', interval = 0.05)
pyautogui.press("enter")
pyautogui.write('matrix = [[0] * num_cols for _ in range(num_rows)]', interval = 0.05)
pyautogui.sleep(10)
pyautogui.press("enter")
pyautogui.press("enter")
pyautogui.write('row_index, col_index = 0, 0', interval = 0.05)
pyautogui.press("enter")
pyautogui.write('while row_index < num_rows and col_index < num_cols:', interval = 0.05)
pyautogui.sleep(10)
pyautogui.press("enter")
pyautogui.write('matrix[row_index][col_index] = min(rowSum[row_index], colSum[col_index])', interval = 0.05)
pyautogui.sleep(10)
pyautogui.press("enter")
pyautogui.press("enter")
pyautogui.write('rowSum[row_index] -= matrix[row_index][col_index]', interval = 0.05)
pyautogui.press("enter")
pyautogui.write('colSum[col_index] -= matrix[row_index][col_index]', interval = 0.05)
pyautogui.sleep(10)
pyautogui.press("enter")
pyautogui.press("enter")
pyautogui.write('if rowSum[row_index] == 0:', interval = 0.05)
pyautogui.press("enter")
pyautogui.write('row_index += 1', interval = 0.05)
pyautogui.press("enter")
pyautogui.press("backspace")
pyautogui.write('else:', interval = 0.05)
pyautogui.press("enter")
pyautogui.write('col_index += 1', interval = 0.05)
pyautogui.sleep(10)
pyautogui.press("enter")
pyautogui.press("enter")
pyautogui.press("backspace")
pyautogui.press("backspace")
pyautogui.write('return matrix', interval = 0.05)
pyautogui.sleep(1)

pyautogui.keyDown("command")
pyautogui.press("enter")
pyautogui.keyUp("command")
pyautogui.sleep(30)
pyautogui.moveTo(810, 260, duration=0)
end_time = time.time()

# Calculate and print the elapsed time
elapsed_time = end_time - start_time
print(f"Elapsed time: {elapsed_time} seconds")
